version: "3.9"

services:

  mysql-db:
    image: mysql:8
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bankdb
      MYSQL_USER: bankuser
      MYSQL_PASSWORD: bankpass
    ports:
      - "3306:3306"

  vsam-api:
    image: vsam-api
    container_name: vsam-api
    depends_on:
      - mysql-db
    ports:
      - "8082:8080"
